### ISSUE TITLE
Failed to setup player upon joining

### ISSUE THREAD

**Issue by HandyHat** [ArkFlame/HamsterAPI#1]
When a player joins, HamsterAPI says
`[HamsterAPI] Failed to setup (player name)! Reason: Tried to access field from a null object`
This started happening from version `0.1.6` - there was no issue on `0.1.5`
Using `Paper-400`
This can be reproduced when the only plugin is HamsterAPI.

**Comment by LucidAPs** [comment]
Same here, and it looks like a lot of people are having the same issue.

**Comment by linsaftw** [comment]
If the plugin doesn't fail in the next injection, ignore the problem. It will almost always fail in the first try.
