### ISSUE TITLE
Failed to inject player on version 1.18

### ISSUE THREAD

**Issue by szprog** [ArkFlame/HamsterAPI#14]
Hi,

Under 1.18 server the plugin constantly comes back with "Failed to inject player [playername] please contact..." message. Easy to recreate the problem, just launch an 1.18 paper server and the plugin will fail. Will it still work though or if the injection is unsuccessful it will not work at all?

**Comment by linsaftw** [comment]
HamsterAPI is not yet compatible with 1.18.

It will probably be implemented in the future, but not at the moment as i don't have too much time available because of work.
