### ISSUE TITLE
1.20 support

### ISSUE THREAD

**Issue by ghost** [ArkFlame/HamsterAPI#16]
because it says 'you can't check, please contact 2ls" spigot
pls unban MISHA#0045 discord arkflame

**Comment by linsaftw** [comment]
It already works with 1.20. (Tested with Purpur 1.20)

**Comment by ghost** [comment]
> It already works with 1.20. (Tested with Purpur 1.20)

tested with spigot

**Comment by linsaftw** [comment]
> > It already works with 1.20. (Tested with Purpur 1.20)
> 
> tested with spigot

Working fine. Incompatible plugin or currupted jar.

**Comment by ghost** [comment]
> > > It already works with 1.20. (Tested with Purpur 1.20)
> > 
> > 
> > tested with spigot
> 
> Working fine. Incompatible plugin or currupted jar.

okay, i test later
pls unban MISHA#0045 discord arkflame

**Comment by ghost** [comment]
@linsaftw [WARNING] [HamsterAPI] Failed to inject player VortexL please contact 2LStudios for support about HamsterAPI as this can lead to vulnerabilities.

[INFO] VortexL joined the game

[INFO] VortexL[/my_ip] logged in with entity id 799 at ([world]44.840995211106566, 69.7431359597822, 119.36297178193404)

ver

[INFO] This server is running CraftBukkit version 3808-Spigot-c62f4bd-44a4b56 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

[INFO] Checking version, please wait...

[INFO] You are 1 version(s) behind

**Comment by ghost** [comment]
in my test server joined my friend

[WARNING] [HamsterAPI] Failed to inject player Drexer please contact 2LStudios for support about HamsterAPI as this can lead to vulnerabilities.

**Comment by ghost** [comment]
on paper works without this message
