### ISSUE TITLE
No 'API-VERSION' Number * API version number is NULL

### ISSUE THREAD

**Issue by narcarsiss** [ArkFlame/HamsterAPI#5]
**Case:** In bukkit.yml, Set Minimum Revision number 1.15, To monitor outdated and unmaintained plugin warnings.

**SERVER:** This server is running Purpur version git-Purpur-1016 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**ERROR:** Could not load 'plugins\HamsterAPI-0.16.jar' in folder 'plugins'

```
org.bukkit.plugin.InvalidPluginException: Plugin API version null is lower than the minimum allowed version. Please update or replace it.
	at org.bukkit.craftbukkit.v1_16_R3.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:352) ~[patched_1.16.5.jar:git-Purpur-1016]
```

**Comment by linsaftw** [comment]
Done
