### ISSUE TITLE
Add 1.17 compatibility

### ISSUE THREAD

**Issue by Mcstudio-technik** [ArkFlame/HamsterAPI#9]
[HamsterAPI] Failed to inject player <player> please contact 2LStudios for support about HamsterAPI as this can lead to vulnerabilities.

**Comment by Mcstudio-technik** [comment]
server version 1.17

**Comment by linsaftw** [comment]
Hello! I am going to test it out...

**Comment by linsaftw** [comment]
I can confirm the same issue. I will see what changed in 1.17.

**Comment by linsaftw** [comment]
Okay I started to make some commits about this, but seems hard to do as Mojang changed every package.

**Comment by Luccboy** [comment]
Hi @linsaftw,
I tried to fix this problem and investigated a bit. I fixed a couple of things and the plugin seems to work fine on 1.17. Here is my code: [https://github.com/Luccboy/HamsterAPI](https://github.com/Luccboy/HamsterAPI). This code may not be good, because I'm not very experienced with Reflections-stuff (that's why I didn't open a PR) but this code may help you fixing this issue.

**Comment by linsaftw** [comment]
> Hi @linsaftw,
> I tried to fix this problem and investigated a bit. I fixed a couple of things and the plugin seems to work fine on 1.17. Here is my code: https://github.com/Luccboy/HamsterAPI. This code may not be good, because I'm not very experienced with Reflections-stuff (that's why I didn't open a PR) but this code may help you fixing this issue.

Hello, thank you for this. We are looking for a way to inject HamsterAPI like ViaVersion does for better security and maintenance.

**Comment by linsaftw** [comment]
As a reminder, we need to implement an injector based on ViaVersion one to properly inject HamsterAPI without incompatibilities in the next versions.

**Comment by rexlManu** [comment]
I would say currently its not really a good idea to upgrade the library because of the mappings. Spigot switched to the mojang mappings. That has the great advantage that you dont need to use reflection anymore because the classes will be same for 1.17 and ongoing versions.

**Comment by linsaftw** [comment]
> I would say currently its not really a good idea to upgrade the library because of the mappings. Spigot switched to the mojang mappings. That has the great advantage that you dont need to use reflection anymore because the classes will be same for 1.17 and ongoing versions.

But we still have to somehow be able to inject on new and old versions.

**Comment by Luccboy** [comment]
Hi @linsaftw,
this is my second attempt to fix this problem: https://github.com/Luccboy/HamsterAPI/commit/7f252012f0c2a27b815b34554c37abe000785128. I changed a few things and I think this code is better to maintain than the last one. I tested it on Spigot 1.8 and 1.17.1 and it works fine. I don't know if this is the best solution for this problem, but it may help you. :)

**Comment by linsaftw** [comment]
> Hi @linsaftw,
> this is my second attempt to fix this problem: [Luccboy@bac370b](https://github.com/Luccboy/HamsterAPI/commit/bac370bb6fd06de9bf590f323c66649642757697). I changed a few things and I think this code is better to maintain than the last one. I tested it on Spigot 1.8 and 1.17.1 and it works fine. I don't know if this is the best solution for this problem, but it may help you. :)

Thank you! This might be a fast solution for now until we get a good decoder like viaversion one. I will review this and implement it if everything is ok.

**Comment by linsaftw** [comment]
fixed on bd43946af7d8d48c53473cc13aaf130a738b878b
